### PR TITLE
update Makefile.PL to use File::Spec->tmpdir to pick the default tmp …

### PR DESCRIPTION
**Pull request by nawglan**
…location.

Addresses Issue #21 

CPAN-PRC pull request.

### CODE REVIEW

**Comment by rivy** [comment]
@nawglan , I think that the patch to allow compilation on 5.26+ would be a good addition to this PR (see https://github.com/rjbs/Data-UUID/issues/24#issuecomment-305788303) for line <https://github.com/rjbs/Data-UUID/pull/32/files#diff-5d3ba18294715d9415e9e732852bfec6R79>.

```
- $d =~ s/\\/\\\\/g if $^O eq 'MSWin32';
+ $d =~ s/\\/\//g if $^O eq 'MSWin32';
```

**Comment by mohawk2** [comment]
I would prefer to just see `$d` be correctly quoted so it survives being used within C, rather than only on `MSWin32`.

**Comment by rivy** [comment]
@mohawk2 , I don't understand what you're asking. I believe the changes (with the above MSWin32 addition) allow compilation on all platforms. (I just wish @rjbs had a moment to merge it.)

**Comment by mohawk2** [comment]
@rivy My point was that your commented patch is taking a valid FS character on Win32, and making it the sort-of-Unix-y version. The thing you want to change, that just quotes `$d` so the `\` is correct, is only being done on Win32, and should actually be done everywhere.

Separately, @rjbs has just released 1.22-TRIAL, which I confirm works on Win32 just great. Hopefully he will release it as a main version really soon! (I don't see the changes in the GH repo though)

MetaCPAN shows the diffs from 1.21 (https://metacpan.org/diff/file?target=RJBS/Data-UUID-1.222-TRIAL/&source=RJBS%2FData-UUID-1.221) with shell-quoting done in a bespoke way. I wish that it would instead use `quote_literal` from https://metacpan.org/pod/ExtUtils::MM_Any#quote_literal-Abstract

**Comment by mohawk2** [comment]
@rivy (and belatedly, I realise that part of the issue is the C stuff needs quoting, but that then also needs shell-quoting, which is done in a per-shell way, which is generally best detected on a per-OS way - but EUMM already has code to deal with that, as mentioned above, and wheel-reinvention is a thing best done cautiously)

**Comment by karenetheridge** [comment]
rude.

**Pull request closed without merging**
